### PR TITLE
ioctx: added ListXattrs()

### PR DESCRIPTION
**Pull request by theanalyst**
Added a function to List Xattrs, which returns a map of all xattrs set
on an object, errors out otherwise

Signed-off-by: Abhishek Lekshmanan <abhishek.lekshmanan@gmail.com>

### CODE REVIEW

**Comment by noahdesu** [comment]
Should ListXattrs return a map from string to byte array (instead of using string type for value), since the function to set extended attributes uses a byte array for the value:

   `func (ioctx *IOContext) SetXattr(object string, name string, data []byte)`

**Comment by theanalyst** [comment]
Yes, I guess it should be a byte array, I have pushed a commit to convert C's char* to GoBytes instead of GoString.(I haven't had much success with trying to start out with a Go Byte array and passing it onto the function by converting to a C char** array.)

Let me know if this is ok

**Comment by noahdesu** [comment]
This looks good to me. The use of char* for blobs in the librados API can usually just be thought of as a void*.

**Comment by theanalyst** [comment]
> This looks good to me. The use of char* for blobs in the librados API can usually just be thought of as a void*.

makes better sense now. Thanks

**Pull request merged**
