### PR TITLE
Add rbd_get_parent_info for image

### PR DESCRIPTION
**Pull request by hustcat**
Signed-off-by: Ye Yin <eyniy@qq.com>

### CODE REVIEW

**Comment by noahdesu** [comment]
Would you mind adding a unit test to rbd_test.go? Thanks!

**Comment by hustcat** [comment]
@noahdesu I added a unit test function for rbd_get_parent_info. Please review it:)

**Comment by noahdesu** [comment]
Thanks @hustcat . I'm going to merge this. I think later it would be good to change the signature of GetParentInfo such that it returned the output parameters, rather than manipulating them through the byte arrays.

**Comment by hustcat** [comment]
Yea, I think so.

**Pull request merged**
