### PR TITLE
Convert some C error code to Go code

### PR DESCRIPTION
**Pull request by hustcat**
Convert some C error code to Go code, for convenient Golang code to handle error.
Define some Rbd constant variables, to pass to librbd API.

Signed-off-by: Ye Yin eyniy@qq.com

### CODE REVIEW

**Comment by noahdesu** [comment]
Hi @gierschv can you take a look at this PR? If we merge this will we need to tag a branch before for docker distribution?

**Comment by gierschv** [comment]
@noahdesu No, the commit id is referenced in the godeps of distribution, no worries :)

**Comment by hustcat** [comment]
@noahdesu I wish this PR can be merged ASAP. Some errors like "ENOENT" is special, we should return specific Go error, It's more convenient for other application.  Such as [here](https://github.com/hustcat/docker-graph-driver/blob/master/driver/rbd/rbd.go#L332).

**Comment by noahdesu** [comment]
Hi @hustcat sorry about the delay reviewing this, and everything looks pretty good. Would you mind updating the other methods in rados.go and rbd.go to return the new error? It looks like only a single function was updated to return the new error object.

**Comment by hustcat** [comment]
@noahdesu Yea, I updated the other functions;)

**Comment by dotnwat** [comment]
Thanks! Merged.

**Pull request merged**
